{"version":1,"ops":[{"type":1,"author":{"id":"ac60f7334d01001923c26a79760643f86dcf4797"},"timestamp":1595533435,"metadata":{"github-id":"MDU6SXNzdWU2NjQ3MjIyMjA=","github-url":"https://github.com/firecat53/keepmenu/issues/56","origin":"github"},"title":"Config parser crashes","message":"Hello I encountered the following error and can not start keepmenu any longer.\nIt occurred after my home partition ran out of space but my config is unaltered under .config/keepmenu/config.ini\nI freed some space and tried reinstalling keepmenu. Also a system reboot didn't help.\n\n\n\n```\n% keepmenu                      \nTraceback (most recent call last):\n  File \"/usr/lib/python3.8/configparser.py\", line 789, in get\n    value = d[option]\n  File \"/usr/lib/python3.8/collections/__init__.py\", line 898, in __getitem__\n    return self.__missing__(key)            # support subclasses that define __missing__\n  File \"/usr/lib/python3.8/collections/__init__.py\", line 890, in __missing__\n    raise KeyError(key)\nKeyError: 'port'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/bin/keepmenu\", line 1421, in \u003cmodule\u003e\n    MANAGER = client()\n  File \"/usr/bin/keepmenu\", line 1231, in client\n    port, auth = get_auth()\n  File \"/usr/bin/keepmenu\", line 174, in get_auth\n    port = int(auth.get('DEFAULT', 'port'))\n  File \"/usr/lib/python3.8/configparser.py\", line 792, in get\n    raise NoOptionError(option, section)\nconfigparser.NoOptionError: No option 'port' in section: 'DEFAULT'\n```","files":null}]}