{"version":1,"ops":[{"type":1,"author":{"id":"52bb437fefd105735e701dc81eb8646e6e633e3f"},"timestamp":1534678906,"metadata":{"github-id":"MDU6SXNzdWUzNTE4OTYxOTI=","github-url":"https://github.com/firecat53/keepmenu/issues/9","origin":"github"},"title":"Connection refused error on launch","message":"Hi,\nFirst thank you for your tool, I can't use it yet, but it looks like a really nice piece of software. The reason why I can't use it is because jwhen running `keepmenu` just after typing my database password I get the following error:\n\n```\nProcess DmenuRunner-2:\nTraceback (most recent call last):\n  File \"/usr/bin/keepmenu\", line 932, in \u003cmodule\u003e\n    MANAGER = client()\n  File \"/usr/bin/keepmenu\", line 758, in client\n    mgr.connect()\n  File \"/usr/lib/python3.7/multiprocessing/managers.py\", line 512, in connect\n    conn = Client(self._address, authkey=self._authkey)\n  File \"/usr/lib/python3.7/multiprocessing/connection.py\", line 492, in Client\n    c = SocketClient(address)\n  File \"/usr/lib/python3.7/multiprocessing/connection.py\", line 619, in SocketClient\n    s.connect(address)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n    self.run()\n  File \"/usr/bin/keepmenu\", line 788, in run\n    self.dmenu_run()\n  File \"/usr/bin/keepmenu\", line 833, in dmenu_run\n    sel = view_all_entries(options, [i for i in self.kpo.entries if not\n  File \"/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py\", line 73, in entries\n    return self.find_entries_by_title('.*', regex=True)\n  File \"/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py\", line 292, in find_entries_by_title\n    first=first\n  File \"/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py\", line 272, in find_entries\n    res = self._find(keys_xp, **kwargs)\n  File \"/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py\", line 159, in _find\n    res = self._xpath(xp, tree=group._element if group else None)\n  File \"/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py\", line 85, in _xpath\n    tree = self.kdb.tree\nAttributeError: 'KDB3Reader' object has no attribute 'tree'\n```\n\nI am using archlinux and installed keepmenu directly thanks to your aur package. Do you have an idea of what is going wrong with my setup?","files":null}]}