{"version":1,"ops":[{"type":1,"author":{"id":"44a0b218d7393260eaabc9384444164cde6f064d"},"timestamp":1552260661,"metadata":{"github-id":"MDU6SXNzdWU0MTkyNDczNjM=","github-url":"https://github.com/firecat53/keepmenu/issues/28","origin":"github"},"title":"'future' module not found","message":"Recently when I was using keepmenu, I noticed that it just refused to start. When I ran `keepmenu` directly in my terminal, it said:\n\n```Traceback (most recent call last):\n  File \"/usr/bin/keepmenu\", line 26, in \u003cmodule\u003e\n    from pykeepass import PyKeePass\n  File \"/usr/lib/python3.7/site-packages/pykeepass/__init__.py\", line 2, in \u003cmodule\u003e\n    from .pykeepass import PyKeePass\n  File \"/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py\", line 8, in \u003cmodule\u003e\n    from future.utils import python_2_unicode_compatible\nModuleNotFoundError: No module named 'future'\n```\n\nI have no idea why this happened. I can only guess that I updated my Arch system via `sudo pacman -Syu` and that might have updated PyKeepass in some way? I updated my system again via `yay -Syu` (for the AUR), but that didn't seem to update keepmenu. In any case, I found the solution already: I just need to install the `future` package via `pip3 install --user future`. However, I am concerned that I had to go out of my way to install something just so keepmenu wouldn't break. \n\nI just wanted to let you know. Perhaps this dependency issue can be worked out?","files":null}]}